### ISSUE TITLE
Slight Typo

### ISSUE THREAD

**Issue by akhilome** [NddyAndy/nddyandy.github.io#1]
Hey, @ndiecodes 👋 

Really nice landing page you've got here. Just a heads up, there's a slight typo on the page (see highlighted text): 

![image](https://user-images.githubusercontent.com/15332525/61993328-296fff00-b062-11e9-99cb-2ab6e555dded.png)

Stay awesome 💪

**Comment by voidnerd** [comment]
Yo! @akhilome , awesome eye you got there. I just fixed this, Thanks for this man :thumbsup:.

**Comment by akhilome** [comment]
Good work, chief. 💃
